<a href="https://colab.research.google.com/github/Mercymerine/24_Data_Analysis/blob/main/Copy_of_Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [ ]:
arr = np.array([1, 2, 3])
result = arr/0
print(result)

[inf inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
from datetime import datetime, timedelta

In [ ]:
today = datetime.now().date()
print(today)

2024-04-30


In [ ]:
yesterday = today - timedelta(days=1)
print(yesterday)

2024-04-29


In [ ]:
tomorrow = today + timedelta(days=1)
print(tomorrow)

2024-05-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import calendar

july_dates = calendar.month(2016, 7)
print(july_dates)

     July 2016
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

#Computing (A + B)
F = (A + B)
print(F)

#Compute (-A/2)
C = (A * -1)
print(C)
D = (C/2)
print(D)

# Compute ((A+B)*(-A/2))
E = (F * D)
print(E)

[ 6  8 10 12]
[-1 -2 -3 -4]
[-0.5 -1.  -1.5 -2. ]
[ -3.  -8. -15. -24.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
#Using as type function
random_array = np.random.rand(5)*10

integer = random_array.astype(int)
print(integer)

[4 9 7 6 1]


In [ ]:
random = np.random.rand(5)*10

integer = np.floor(random)

print(integer)

[8. 9. 1. 8. 4.]


In [ ]:
random = np.random.rand(5)*10

integer = np.trunc(random)

print(integer)

[7. 4. 8. 7. 1.]


In [ ]:
random = np.random.rand(5)*10

for x in random:
  print(int(x))

8
6
3
0
4


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
array = np.random.randint(0, 4, size = (5, 5))
print(array)

[[1 2 1 1 1]
 [0 2 2 0 2]
 [1 0 1 0 2]
 [3 3 2 3 0]
 [0 0 0 1 3]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
    array = []
    for values in range(10):
        array.append(values)
    print(array)



In [ ]:
print(generator())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
None


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
array =  np.random.random(10)
print(array)

[0.99265344 0.22121396 0.2879082  0.46792679 0.47635321 0.27727302
 0.27622594 0.71540813 0.04699722 0.69536617]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vector = np.random.randint(56, 79, 10)
print(np.sort(vector))

[63 63 64 64 68 70 71 71 74 76]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(sum(array))

55


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
aA = np.random.randint(0, 10, 5)
bB = np.random.randint(0, 10, 5)

print(aA == bB)

[False  True False False False]


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
x = [1, 2, 3, 4, 5]
y = tuple(x)
print(y)

#Raises an error
#y[0] = 6
#print(y)

(1, 2, 3, 4, 5)


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
#Generate random Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

#Split x and y coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

#Convert to polar coordinates
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

#Dispaly the results
polar_coords = np.column_stack((r, theta))
print('Cartesian Coordinates')
print(cartesian_coords)
print('\nPolar Coordinates')
print(polar_coords)




Cartesian Coordinates
[[0.4810174  0.62580097]
 [0.63694135 0.09849204]
 [0.95186874 0.72278476]
 [0.57161047 0.61075688]
 [0.79278239 0.32859352]
 [0.18772278 0.03876136]
 [0.337754   0.35725776]
 [0.10470616 0.68437603]
 [0.20347433 0.11749175]
 [0.16362312 0.13446444]]

Polar Coordinates
[[0.7893064  0.91547021]
 [0.64451142 0.15341772]
 [1.19518698 0.64944713]
 [0.83651808 0.81849458]
 [0.85818275 0.39292764]
 [0.19168277 0.20362035]
 [0.49164099 0.81345329]
 [0.69233946 1.4189785 ]
 [0.23495982 0.52365699]
 [0.21178577 0.6878892 ]]


In [ ]:
'''
Now, you want to tell someone where a different dot is on that paper. Instead of saying, "Go 2 steps to the right and 3 steps up," which is like using a map grid (like x and y coordinates), you could say something like, "Go out 5 steps from the center and then turn 30 degrees to the left."

So, polar coordinates are like giving directions from the center of that paper (or dartboard), saying how far out you go (the distance) and which way you turn (the angle), instead of just saying how many steps you go in each direction (like x and y coordinates). It's just another way to talk about where things are!

'''

'\nNow, you want to tell someone where a different dot is on that paper. Instead of saying, "Go 2 steps to the right and 3 steps up," which is like using a map grid (like x and y coordinates), you could say something like, "Go out 5 steps from the center and then turn 30 degrees to the left."\n\nSo, polar coordinates are like giving directions from the center of that paper (or dartboard), saying how far out you go (the distance) and which way you turn (the angle), instead of just saying how many steps you go in each direction (like x and y coordinates). It\'s just another way to talk about where things are!\n\n'

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
array = np.random.randint(88, 98, 10)
print(array)


for values in array:
    if values == array.max():
        print(0)


[93 89 97 89 97 97 91 88 89 94]
0
0
0
