<a href="https://colab.research.google.com/github/Mercymerine/24_Data_Analysis/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr)

#Calcualte the shape of the array
rows, columns = arr.shape
print(rows, columns)

#Creating a new array with dimensions increased by 2 to accomodate the border
bordered = np.zeros((rows + 2, columns + 2), dtype = arr.dtype)

#Copy the original array into the center of the bordered array
bordered[1:-1, 1:-1] = arr

print(bordered)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3 3
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan) # operation results in nan (not a number) because any arithmetic operation involving nan results in nan.
print(np.nan == np.nan) #nan is considered not equal to itself. This is because nan represents an undefined or unrepresentable value, so it's not logically equal to any other value, including itself.
print(np.inf > np.nan) #In this case, np.inf represents positive infinity, which is greater than any finite number. However, when compared to nan, the result is False, as any comparison involving nan results in False.
print(np.nan - np.nan) #operation results in nan. Subtracting nan from nan results in nan because the value is undefined.
print(np.nan in set([np.nan])) #This membership check returns True. Although nan is not equal to itself in a direct comparison, it is considered to be a member of a set containing nan.
print(0.3 == 3 * 0.1) #comparison returns False. This is because floating-point arithmetic can sometimes introduce small errors due to the way numbers are represented in binary. In this case, 3 * 0.1 does not result in exactly 0.3 due to such precision issues.

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
arr = np.zeros((5, 5))
print(arr)

#Set the values 1, 2,3, 4 just below the diagnol
np.fill_diagonal(arr[1:], [1, 2, 3, 4]) #np.fill_diagonal() function is used to fill the diagonal starting from the first sub-diagonal with the specified values.

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
arr = np.random.randint(8, size=(4, 4))
print(arr)
print(arr[::2, ::2])

[[7 3 7 6]
 [2 7 7 5]
 [7 3 2 5]
 [6 4 1 3]]
[[7 7]
 [7 2]]


In [ ]:
#Create an 8*8  matrix filled with zeros
matrix = np.zeros((8, 8), dtype = int)
print(matrix)

#Fill the matrix with the checkerboard pattern
matrix[::2, ::2] = 1 # Fill every other row and column with 1 starting from (0,0)
print(matrix)

matrix[1::2, 1::2] = 1 #Fill every other row and column with 1 starting from(1,1)
print(matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
arr = np.arange(336).reshape(6, 7, 8)
print(arr)
print(arr[1, 5, 3])

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
arr = np.random.normal(1, 0.5, size=(5, 5))
print(arr)

[[0.25368721 0.68519361 1.220988   0.21150713 0.70736757]
 [1.01794563 1.23056965 1.47092836 0.97606859 0.93727043]
 [1.63794629 0.62439833 1.58580567 0.92362017 0.88729243]
 [1.31248212 0.98404275 0.7608424  1.38046122 1.35908375]
 [0.67602153 1.25418818 0.77714186 1.65619777 2.12415285]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
custom_matrix = np.array([
    [[2, 4, 6], [4, 7, 0]],
    [[1, 2, 3], [5, 8, 6]],
    [[0,9, 8], [7, 6, 5]],
    [[4, 3, 2], [1, 1, 1]]
])
print(custom_matrix)
print(custom_matrix.ndim)

[[[2 4 6]
  [4 7 0]]

 [[1 2 3]
  [5 8 6]]

 [[0 9 8]
  [7 6 5]]

 [[4 3 2]
  [1 1 1]]]
3


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
arr1 = np.arange(15).reshape(5,3)
print(arr1)

arr2 = np.arange(6).reshape(3, 2)
print(arr2)

arr3 = arr1 * arr2
print(arr3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


ValueError: operands could not be broadcast together with shapes (5,3) (3,2) 

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.arange(10)
print(arr)
arr[(arr>3) & (arr<8)] *= -1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))

#?? he behavior is similar to the previous line, but with NumPy's sum function, you'll get an output that is converted to a NumPy array.
from numpy import *
x = (sum(range(5),-1))
print(dtype(x))

10
int32


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#Z =np.array([1, 2, 3])
Z = 5
print(Z**Z)# This expression calculates the element-wise exponentiation of vector Z to itself. It raises each element of Z to the power of itself. This is legal, assuming Z is a vector with integer elements.
print(2 << Z >> 2) #This expression left shifts each element of Z by 2 bits (2 << Z) and then right shifts the result by 2 bits (>> 2). This operation is legal as long as the elements of Z are integers.
print(Z <- Z) #  This expression checks element-wise if each element of Z is less than minus itself. It's a comparison operation. This is legal, assuming Z is a vector with integer elements.
print(1j*Z) #This expression multiplies each element of Z by the imaginary unit 1j. It's legal as long as Z is a vector with numerical elements (either integer or floating-point).
print(Z/1/1) # This expression divides each element of Z by 1 and then by 1 again. It's legal as long as Z is a vector with numerical elements (either integer or floating-point).
print(Z<Z>)#  This line of code is incomplete and contains a syntax error. The < operator expects another value after it for comparison. It seems like there's a typo or missing expression after the second <
#Correct code
print(Z<Z>Z)

3125
16
False
5j
5.0
False


## Question??

In [ ]:
print(8 << Z >> 8)

0


In [ ]:
print(7 << Z >> 7)

0


In [ ]:
print(6 << Z >> 6)

1


In [ ]:
print(5 << Z >> 5)

2


In [ ]:
print(4 << Z >> 4)

4


In [ ]:
print(3 << Z >> 3)

6


In [ ]:
print(2 << bZ >> 2)

8


In [ ]:
print(1 << Z >> 1)

8


In [ ]:
print(0 << Z >> 0)

0


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(5//5)

1


In [ ]:
print(np.array(0) / np.array(0))#  this operation results in a division by zero error, which is mathematically undefined. This is because dividing zero by zero does not have a meaningful mathematical interpretation.Result: nan
print(np.array(0) // np.array(0)) #Similarly to the previous case, this operation also results in a division by zero error. NumPy handles this situation by producing a warning and returning zero as a result. This is because floor division of zero by zero is undefined, but NumPy chooses to return zero as a convention.Result: 0
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Mercy Atiz\AppData\Local\Temp\ipykernel_44620\1347146650.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))#  this operation results in a division by zero error, which is mathematically undefined. This is because dividing zero by zero does not have a meaningful mathematical interpretation.Result: nan
C:\Users\Mercy Atiz\AppData\Local\Temp\ipykernel_44620\1347146650.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Mercy Atiz\AppData\Local\Temp\ipykernel_44620\1347146650.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
print(np.ceil(4.1)) # Round up to the next integer. For Positive numbers

-4.0


In [ ]:
print(np.floor(4.99)) #Round down to the next integer. For Negative numbers

-5.0


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
#arr3 = np.array([3, 4, 5, 9, 10])

#Find common values
common_values = np.intersect1d(arr1, arr2) # takes two arrays as input and returns the sorted, unique values that are present in both arrays.
print(common_values)

[3 4 5]
