<a href="https://colab.research.google.com/github/Mercymerine/24_Data_Analysis/blob/main/Numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
#Array
array = np.array([1, 3, 5, 7, 9])

#Given value
given_value = 6

#Absolute difference
diff = np.abs(array - given_value)
print(diff)

#Index of the minimum absolute difference
index = np.argmin(diff)
print(index)


#Nearest value
nearest_value = array[index]

print(array)
print(nearest_value)

[5 3 1 1 3]
2
[1 3 5 7 9]
5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
#???????????????????????

In [ ]:
array1 = np.random.randint(10)
array2 = np.random.randint(10)

print(np.sum(array1 + array2))

14


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class Array_class():
    def __init__(self, name):
        self.name = name

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
import numpy as np

#Given vector
given_vector = np.array([10, 20, 30, 40, 50])

#Indices vector
indices_vector = np.array([0, 1, 1, 3, 4])

#Add 1 to each element indexed by the second vector
for index in np.unique(indices_vector):
    given_vector[index] +=1
print(given_vector)

[11 21 30 41 51]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
import numpy as np

array = np.random.randint(0, 20, size = (2, 3, 4, 5))
print(array)



axis_sum = np.sum(array, axis=(-2, -1))#??????????
print(axis_sum)

[[[[ 2 19 10  5  6]
   [14 19  4  0 18]
   [14  0  6  0 19]
   [15 12 11 12 16]]

  [[19 13 12  6  3]
   [15 16 19  3 19]
   [ 1 10 19  6 16]
   [ 4  6 13  9  5]]

  [[14 11  3  8  0]
   [17 12  1 12 12]
   [ 9  1 10 16 13]
   [ 7 16  4 11  3]]]


 [[[16  8  2 17 18]
   [13  6  5  3 13]
   [ 1 10 14 18 17]
   [11 15  4  6  3]]

  [[12 10 18  3 16]
   [ 0  0  5 17 12]
   [ 2  1 11 19  3]
   [ 1  5 13 15  9]]

  [[11  5  5 17 14]
   [ 9 15 16 15 14]
   [ 0 11  9 18  7]
   [11 19  9  6 17]]]]
[[202 214 180]
 [200 172 228]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
arr1 = np.array([[1, 2],
                [4, 5]])

arr2 = np.array([[7, 8],
               [9, 10]])

#Diagonal of the dot product of A and B
print((np.dot(arr1, arr2)))
dot_product = np.diag(np.dot(arr1, arr2))
print(dot_product)

[[25 28]
 [73 82]]
[25 82]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
array1 = np.array([[[1, 2, 3],
           [4, 5, 6]]])
array2 = np.array([[1, 2,3],
                  [4, 5, 6]])
print(array1)
print(array2)
new=array2[:, :, np.newaxis] #This part of the code adds a new axis to the 2D array. By using np.newaxis, we're essentially adding a new dimension to the 2D array along the third axis.
print(new)
print(new.ndim)

[[[1 2 3]
  [4 5 6]]]
[[1 2 3]
 [4 5 6]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
3


In [ ]:
arr1 = np.random.randint(0, 4, size = (5, 5, 3))
arr2 = np.random.randint(0, 4, size= (5, 5))

print(arr1 * arr2[:, :, np.newaxis])

[[[2 3 2]
  [2 0 3]
  [3 3 0]
  [1 2 0]
  [0 3 9]]

 [[0 0 0]
  [0 6 2]
  [0 3 3]
  [4 6 2]
  [3 1 2]]

 [[3 1 1]
  [3 1 1]
  [4 2 4]
  [3 0 3]
  [0 9 0]]

 [[2 2 1]
  [2 0 0]
  [4 2 0]
  [0 6 6]
  [9 6 9]]

 [[3 6 9]
  [6 3 6]
  [3 0 3]
  [4 0 4]
  [0 6 2]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


print(array[[0, 1]])
print('********')
print(array[[1, 0]])
print('********')
array[[0, 1]] = array[[1, 0]]
print(array)

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [1 2 3]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
#?????????????????????

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
#???????????????

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
#???????????????

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
#??????????

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
boolean = True
boolean = not boolean
print(boolean)


False


In [ ]:
number = 5.0
number = - number
print(number)

-5.0


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [ ]:
#???????????????

In [ ]:
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

rank = np.linalg.matrix_rank(matrix)
print(rank)

2


#### 83. How to find the most frequent value in an array?

In [ ]:
#???????????????

In [ ]:
arrays = np.array([1, 2, 3, 4, 2, 2, 3, 3, 3])

#Finding the most frequent value
value = np.bincount(arrays).argmax()
print(value)

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
#???????????????????????

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
#?????????????

In [ ]:
#Assume n = 5

arr1 = np.random.randint(0, 5, size=(5, 5))
arr2 = np.random.randint(0, 5, size =(5, 1))

product = (arr1 * arr2)
print(product)

[[ 8  0  0  8 16]
 [12  0 12  8  0]
 [ 9  0  0  3  9]
 [ 0 12 12  0  0]
 [ 3  2  2  3  2]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
#?????????????????

In [ ]:
array = np.random.randint(1, 10, (16, 16))


#Block size
block_size = 4

#Reshape array into a 4D array 0f shape (4, 4, 4, 4)
reshaped_array = array.reshape(4, 4, 4, 4)

#Getting sum
block_sum = reshaped_array.sum(axis=(-2, -1))
print(block_sum)

[[90 92 92 85]
 [93 96 80 78]
 [88 78 60 81]
 [85 66 76 88]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
#?????????????????

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
array = np.array([1, 5, 3, 9, 7, 2, 8, 4, 6])

#Number of largest value to retrieve
n=3

#Get the n largest values of array
largest_values = np.sort(array)[-n:]
print(largest_values)

[7 8 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
import itertools # provides various functions for working with iterators and combinatorial functions.

In [ ]:
vectors = [[1, 2, 3], [4, 5], [6, 7]]

#Buiding the cartesian product
cartesian = list(itertools.product(*vectors)) # It takes multiple iterables (in this case, vectors) as arguments and returns an iterator that produces tuples containing all possible combinations of items from the input iterables. The *vectors syntax is used to unpack the list of vectors into separate arguments for the itertools.product function.
print(cartesian)

[(1, 4, 6), (1, 4, 7), (1, 5, 6), (1, 5, 7), (2, 4, 6), (2, 4, 7), (2, 5, 6), (2, 5, 7), (3, 4, 6), (3, 4, 7), (3, 5, 6), (3, 5, 7)]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
#?????????///

In [ ]:
array = np.array([[1, 'John', 25],
                 [2, 'Alice', 30],
                 [3, 'Bob', 35]])

#Defining the dtype for the record array
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

for row in array:
    x = ([tuple(row)])
    print(x)
    print('**********')
    print(np.array(x))

[('1', 'John', '25')]
**********
[['1' 'John' '25']]
[('2', 'Alice', '30')]
**********
[['2' 'Alice' '30']]
[('3', 'Bob', '35')]
**********
[['3' 'Bob' '35']]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
#Method 1 using np.power
Z = np.random.rand(1000000)

ZP = np.power(Z, 3)
print(ZP)


[3.17095722e-01 6.17552154e-05 8.41792220e-01 ... 2.74789362e-03
 6.05884556e-01 4.59904324e-01]


In [ ]:
#MEthod 2 using **
ZE = (Z ** 3)
print(ZE)

[3.17095722e-01 6.17552154e-05 8.41792220e-01 ... 2.74789362e-03
 6.05884556e-01 4.59904324e-01]


In [ ]:
#Method 3: *
ZM = Z * Z * Z
print(ZM)

[3.17095722e-01 6.17552154e-05 8.41792220e-01 ... 2.74789362e-03
 6.05884556e-01 4.59904324e-01]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [1, 2, 3],
                  [4, 5, 6]])
B = np.array([[2, 1],
             [5, 4]])

#Sort the rows of B
sorted_B = np.sort(B, axis =1)

#Sort the rows of A
sorted_A = np.sort(A, axis = 1)

matching_rows = np.all(np.isin(sorted_A[:, :, None], sorted_B.T), axis = 1).any(axis = 1)
result = A[matching_rows]
print(result)



[]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
lists = [1, 2, 3, 4, 5, 2, 3]
print(lists)
x = set(lists)
print(x)
print(len(x))

[1, 2, 3, 4, 5, 2, 3]
{1, 2, 3, 4, 5}
5


In [ ]:
matrix = np.array([[1, 1, 1],
                  [2, 2, 1],
                  [3, 3, 3],
                  [4, 4, 4],
                  [4, 5, 5],
                  [7, 4, 3],
                  [6, 6, 6],
                  [8, 8, 8],
                  [9, 9, 9],
                  [9, 5, 6]])
unequal_list =[]

for row in matrix:
    # If the length of the set of values in the row is not equal to 1,
    # it means there are unequal values in the row
        if len(set(row)) != 1:#??????
            unequal_list.append(row)

for row in unequal_list:
    print(len (row))

3
3
3
3


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
vector = np.array([0, 2, 3, 4])

#Maximum value
max_value = np.max(vector)

#Create a matrix of zeros with shape(len(vector)=row, max_value=columns)
matrix = np.zeros((len(vector), max_value), dtype = int)

for i, val in enumerate(vector):
    matrix[i, :val] = 1 #i = index, val: value of index, =1: assigns the the value 1 to the selected elements
print(matrix)


[[0 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]


In [ ]:
enumerate?


Init signature: enumerate(iterable, start=0)
Docstring:     
Return an enumerate object.

  iterable
    an object supporting iteration

The enumerate object yields pairs containing a count (from start, which
defaults to zero) and a value yielded by the iterable argument.

enumerate is useful for obtaining an indexed list:
    (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
Type:           type
Subclasses:     

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
array = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [1, 2, 3],
                 [7, 8, 9],
                 [4, 5, 6]])
print(np.all(np.unique(array)))

True


In [ ]:
array = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [1, 2, 3],
                 [7, 8, 9],
                 [4, 5, 6]])

#Convert the 2D array to a list of tuples(each row becomes a tuple)
# tuples = [tuple(row) for row in toys]
tuple_list = []
for row in array:
    # Each row of the array becomes a tuple. This step is necessary because NumPy's unique() function works differently with 2D arrays.
    x = tuple(row)
    tuple_list.append(x)
print(tuple_list)

# We use the set() function to get unique tuples. A set is a collection of unique elements, so when we convert the list of tuples to a set, it automatically removes duplicates.
unique = np.array(list(set(tuple_list)))
print(unique)

[(1, 2, 3), (4, 5, 6), (1, 2, 3), (7, 8, 9), (4, 5, 6)]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

#Inner product using einsum
# Imagine you have two lists of numbers, and you want to multiply each pair of numbers from the two lists, then add up all those products.
inner_product = np.einsum('i, i->', A, B) # 'i,i->' indicates that we want to multiply corresponding elements of A and B, and -> indicates that we want to sum up the results.
print(inner_product)

32


In [ ]:
#???????

In [ ]:
#Outer product using einsum
#imagine you have two lists again, but this time you want to create a matrix where each element (i, j) is the product of the ith element of the first list and the jth element of the second list.

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

#Outer product using einsum
outer_product = np.einsum('i, j->ij', A, B)
print(outer_product)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
#Sum
# Let's say you have a list of numbers and you want to add them all up. That's the sum

X = np.array([1, 2, 3, 4, 5])

#Sum using einsum
total_sum = np.einsum('i->', X)
print(total_sum)

15


In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

#Multiplication einsum
mul = np.einsum('i, i->i', A, B)
print(mul)

[ 4 10 18]


In [ ]:
#np.einsum?


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
#????????????????????

In [ ]:
Y = np.array([1, 4])
X = np.array([2, 0])

diff = (Y - X)
print(diff/2)

[-0.5  2. ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
# Let's say this is our 2D array X representing boxes and their balls
X = np.array([[1, 2, 3],
             [2, 3.5, 4],
             [0, 5, 6],
             [4, 1, 0]])

# Our desired total count of balls in each box
n = 6

# List to store the rows that meet our conditions
selected_rows = []

# Loop through each row in X
for row in X:
    #Check if the row contains only integers and if the sum equals n
    if np.all(np.equal(np.mod(row, 1), 0)) and np.sum(row) == n:
        selected_rows.append(row)

for row in selected_rows:
    print(row)

[1. 2. 3.]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.array([3, 5, 7, 9, 1, 13, 15])

#Samples
N = 1000

#List to store the means of each sample
sample_means = []

#Loop N times to take samples, compute their mean and store it
for i in range(N):
    #Randomly sample withreplacement form the bag
    sample = np.random.choice(X, size=len(X), replace=True)
    #print(sample)
    #Compute the mean of the sample and add it to the list
    sample_mean = (sample)
    #print(sample_mean)
    sample_means.append(sample_mean)
   # print(sample_means)

#Compute the 2.5th and 97.5th percentile to get the 95% confidence interval
lower_bound = np.percentile(sample_means, 2.5)
upper_bound = np.percentile(sample_means, 97.5)
print(f'Interval for the mean: {lower_bound}, {upper_bound}')

Interval for the mean: 1.0, 15.0
