<a href="https://colab.research.google.com/github/Mercymerine/24_Data_Analysis/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
print(np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Mercy Atiz/AppData/Local/anaconda3/Library/include
    lib directory: C:/Users/Mercy Atiz/AppData/Local/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print(null_vector.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np?


Type:        module
String form: <module 'numpy' from 'C:\\Users\\Mercy Atiz\\AppData\\Local\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\mercy atiz\appdata\local\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.arange(10, 49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
reverse_vector = np.arange(10)
print(np.flip(reverse_vector))

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr = np.random.randint(0, 8, size =(3, 3))
print(arr)


[[3 4 1]
 [7 4 4]
 [1 4 0]]


In [ ]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array = np.array([1, 2, 0, 0, 4, 0])
for values in array:
    if values != 0:
        print(values)

1
2
4


In [ ]:
array = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(array))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.85764996 0.65269463 0.42374344]
  [0.31628049 0.24505689 0.62495274]
  [0.26561893 0.48685334 0.36058411]]

 [[0.94153548 0.5541206  0.25971294]
  [0.0703755  0.0948277  0.91923986]
  [0.64643032 0.95980432 0.95747699]]

 [[0.30937954 0.62688522 0.94933082]
  [0.48626352 0.36359802 0.28088976]
  [0.22544734 0.89042603 0.57271917]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr = np.random.random((10, 10))
print(arr)

[[0.72556547 0.55158511 0.80811182 0.19174746 0.82937284 0.29868988
  0.12837183 0.22312756 0.08108382 0.56608092]
 [0.00156924 0.27966489 0.14620428 0.10523479 0.45199155 0.6365388
  0.76979649 0.37078743 0.79405218 0.57113207]
 [0.39102823 0.09234568 0.59612174 0.46089974 0.12373922 0.32807231
  0.30498245 0.59480644 0.76707797 0.4593209 ]
 [0.56524246 0.62657626 0.59441015 0.15845138 0.50192188 0.55916993
  0.12346657 0.59524819 0.052827   0.12262107]
 [0.92686991 0.79921614 0.17037799 0.20062021 0.58711892 0.78678183
  0.56707842 0.76885461 0.49789606 0.32375192]
 [0.46201139 0.00791024 0.1379815  0.03492485 0.206583   0.31589141
  0.53937179 0.40171457 0.50127379 0.33978888]
 [0.94085852 0.64316898 0.11739248 0.32415533 0.81773299 0.79433006
  0.68602479 0.78592716 0.70972528 0.36368153]
 [0.39236153 0.60170577 0.02808753 0.92307017 0.11155339 0.69968767
  0.05059109 0.17776676 0.27617045 0.41481634]
 [0.95610434 0.01784456 0.02678098 0.48294978 0.01642582 0.39063953
  0.1045391  

In [ ]:
arr.max()

0.9624406217568627

In [ ]:
arr.min()

0.0015692361778920638

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr = np.random.random(30)
print(arr)

[[0.51572881 0.11960298 0.42354551 0.61042644 0.50653679 0.98687758
  0.4795675  0.78292092 0.10506879 0.11234317 0.96824264 0.2859835
  0.48754079 0.29473792 0.81364751 0.8442513  0.74914635 0.61243712
  0.77776215 0.81248016 0.28400215 0.37907939 0.94788233 0.77837525
  0.05064853 0.0850512  0.90651604 0.79283948 0.41897439 0.61088739]
 [0.89739514 0.4145821  0.44289095 0.34097242 0.37742966 0.17965618
  0.80744487 0.99870835 0.78379901 0.35396504 0.14395369 0.9469971
  0.87183738 0.43579013 0.74802668 0.36320603 0.29933483 0.9724037
  0.40157597 0.84344211 0.40545107 0.83970713 0.01939568 0.37651461
  0.21275996 0.3033107  0.09352746 0.5581993  0.51608548 0.60720477]
 [0.6902634  0.80000248 0.00835783 0.17306772 0.77974217 0.82988533
  0.22320028 0.40087714 0.6865498  0.80850505 0.53255381 0.13251937
  0.7011171  0.8162485  0.01755847 0.88846142 0.28174055 0.39434145
  0.43145106 0.06419163 0.76509059 0.87110349 0.98571268 0.91957702
  0.75852252 0.75881912 0.7526867  0.65697652 0.2

In [ ]:
arr.mean()

0.5315937639586593

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
values = [
    [1, 0, 1],
    [1, 0, 1],
    [1, 0, 1],
]
matrix = np.array(values)
print(matrix)

[[1 0 1]
 [1 0 1]
 [1 0 1]]
