<a href="https://colab.research.google.com/github/Mercymerine/24_Data_Analysis/blob/main/Numpy_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Basic Numpy Operations**

In [ ]:
import numpy as np

### Reshaping Arrays

In [ ]:
#Giving a new shape to an array without changing its data

arr = np.array([[1, 2, 3, 7, 8], [4, 5, 6, 9, 10]])
print(f"Shape : {arr.shape}")
print(arr)
print("\n")

arr2 = arr.reshape(5, 2)
print(f"Arr 2 shape : {arr2.shape} ")
print(arr2)

Shape : (2, 5)
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


Arr 2 shape : (5, 2) 
[[ 1  2]
 [ 3  7]
 [ 8  4]
 [ 5  6]
 [ 9 10]]


Why Do They Look Similar?
arr.reshape(-1): This flattens the array into a 1D list of numbers. It has no rows or columns anymore—just 6 elements in one dimension.
arr.reshape(1, -1): This keeps it as a 2D array with 1 row and 6 columns.

In [ ]:
arr3 = arr.reshape(-1)
print(f"Arr 3 shape : {arr3.shape}")
print(arr3)

Arr 3 shape : (10,)
[ 1  2  3  7  8  4  5  6  9 10]


In [ ]:
arr5 = arr.reshape(1, -1)
print(f"Arr 5 shape : {arr5.shape}")
print(arr5)

Arr 5 shape : (1, 10)
[[ 1  2  3  7  8  4  5  6  9 10]]


In [ ]:
arr4 = arr.reshape(-1, 1)
print(f"Arr 4 shape : {arr4.shape}")
print(arr4)

Arr 4 shape : (10, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 7]
 [ 8]
 [ 4]
 [ 5]
 [ 6]
 [ 9]
 [10]]




*   arr.reshape(-1, 1): Creates a column vector.
*   arr.reshape(1, -1): Creates a row vector.
*   arr.reshape(-1): Flattens the array into a 1D array.






### Concatenation

axis=1: Concatenates along columns, adding the arrays side by side, resulting in one row.
axis=0: Concatenates along rows, adding the arrays one below the other, resulting in multiple rows.

In [ ]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])

concatenated_array = np.concatenate((arr1, arr2), axis=1)
concatenated_array

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])

concatenated_array = np.concatenate((arr1, arr2), axis=0)
concatenated_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])

concatenated_array = np.concatenate((arr1, arr2), axis=None)
concatenated_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])
arr3 = np.array([[7, 8, 9]])



concatenated_array = np.concatenate((arr1, arr2, arr3), axis=0)

print('Array 1:', arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)
print("Concatenated Array", concatenated_array)

Array 1: [[1 2 3]]
Array 2: [[4 5 6]]
Array 3: [[7 8 9]]
Concatenated Array [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6]])

arr4 = np.concatenate((a, b), axis=None)
print(a.ndim)
print(arr4.ndim)


2
1


In [ ]:
c = a.flatten()
c.ndim

1

In [ ]:
a.ndim

2

In [ ]:
arr1.ndim

2

1D arrays like arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]) are simple lists of numbers. They only have one axis (axis=0), which represents the elements themselves.
When you specify axis=1, NumPy expects the arrays to be at least 2D (where axis=1 refers to columns), but since you're working with 1D arrays, it raises an error: "axis 1 is out of bounds for array of dimension 1".

In [ ]:
arr1 = np.array([1, 2, 3])
arr1.ndim

1

In [ ]:
arr1 = np.array([[1, 2, 3]])
arr1.ndim

2

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concatenated_array = np.concatenate((arr1, arr2), axis=None)

print("Array 1", arr1)
print("Array 2", arr2)
print("Concatenated Array", concatenated_array)

Array 1 [1 2 3]
Array 2 [4 5 6]
Concatenated Array [1 2 3 4 5 6]


- Reshape(-1, 1) results in an array with a single column and multiple rows (a column vector), while reshape(1, -1) results in an array with a single row and multiple columns (a row vector).

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#Reshaping the arrays to 2D (each array becomes a row vector)
arr1_reshaped = arr1.reshape(1, -1)
arr2_reshaped = arr2.reshape(1, -1)

concatenated_array = np.concatenate((arr1_reshaped, arr2_reshaped), axis=1)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Concatenated Array:", concatenated_array)

Array 1: [1 2 3]
Array 2: [4 5 6]
Concatenated Array: [[1 2 3 4 5 6]]


In [ ]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Concatenate along rows
result = np.concatenate((array1, array2), axis=0)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

#Concatenate along columns
result = np.concatenate((array1, array2), axis=1)
print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7]])

In [ ]:
np.concatenate((a, b), axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
np.concatenate((a, b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6, 7])

## **Operations on a single array**

In [ ]:
num = [1, 2, 3, 4]
add = 1

for i in num:
  sum = i + add
  print(sum)

2
3
4
5


In [ ]:
num + add

TypeError: can only concatenate list (not "int") to list

In [ ]:
a = np.array([1, 2, 5, 3])

#Add 1 to every element
print("Adding 1 to every element", a+1)

#Subtract 3 from each element
print("Subtracting 3 from element", a-3)

#Multiply each element by 10
print("Multiplying each element by 10:", a*10)

#Square Each element by 10
print("Squaring each element:", a**2)

Adding 1 to every element [2 3 6 4]
Subtracting 3 from element [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]


In [ ]:
a = [1, 2, 5, 3]
print(type(a))
print(a+1)

<class 'list'>


TypeError: can only concatenate list (not "int") to list

In [ ]:
a = np.array([1, 2, 5, 3])
print(type(a))
print(a+1)

<class 'numpy.ndarray'>
[2 3 6 4]


In [ ]:
import numpy as np
import time

# Create a large dataset
size = 10**8
python_list = list(range(size))
numpy_array = np.array(python_list)

# Sum using Python list
start_time = time.time()
python_sum_list = sum(python_list)  # Make sure 'sum' is not defined elsewhere
end_time = time.time()
python_list_time = end_time - start_time

# Sum using NumPy array
start_time = time.time()
numpy_array_sum = np.sum(numpy_array)
end_time = time.time()
numpy_array_time = end_time - start_time

print(f"Sum using Python List: {python_sum_list}, Time: {python_list_time:.6f} seconds")
print(f"Sum using NumPy Array: {numpy_array_sum}, Time: {numpy_array_time:.6f} seconds")


Sum using Python List: 4999999950000000, Time: 0.470874 seconds
Sum using NumPy Array: 4999999950000000, Time: 0.045333 seconds


In [ ]:
type(python_list)

list

In [ ]:
num= [1, 2, 3, 4]
print(sum(num))

10


In [ ]:
del sum

Methods

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

#Sum of all elements
sum_elements = np.sum(arr)

#Mean of all elements
mean_value = np.mean(arr)

#Maximum element
max_value = np.max(arr)

#Minimum element
min_value = np.min(arr)

#Median of array
median_value = np.median(arr)

print('Original array', arr)
print('Sum', sum_elements)
print('Mean',mean_value)
print('Max', max_value)
print('Min', min_value)
print('Median', median_value)

Original array [1 2 3 4 5]
Sum 15
Mean 3.0
Max 5
Min 1
Median 3.0


**Vectorization (Arrays vs Lists)**

Vectorization in NumPy refers to the practice of using array operations that apply to entire arrays or large blocks of data at once, rather than using explicit loops. This approach allows for more efficient computation and leads to cleaner, more readable code.

**Key Benefits of Vectorization:**

*  ** Performance:** Vectorized operations are generally faster than iterating over elements with loops, as they take advantage of low-level optimizations and parallel processing.

*   **Conciseness:** Vectorized code is often more concise and easier to read compared to traditional loop-based implementations.
*  ** Functionality:** Many mathematical operations and functions in NumPy are already vectorized, allowing you to perform complex calculations with minimal code.


Common Vectorized Operations:

*   Element-wise operations: Addition, subtraction, multiplication, division, etc.
*   Aggregations: Functions like np.sum(), np.mean(), np.std(), etc.

* Broadcasting: Allows operations between arrays of different shapes.

In [ ]:
#Creating two python lists
a_list = [1, 2, 3, 4, 5]
b_list = [6, 7, 8, 9, 10]

#Element-wise addition using a loop
result_list = []
for i in range(len(a_list)):
  result_list.append(a_list[i] + b_list[i])

print(result_list)

[7, 9, 11, 13, 15]


In [ ]:
# Creating two NumPy arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

# Element-wise addition using vectorization
#result = a + b

print(a+b)

[ 7  9 11 13 15]


**Broadcasting:** The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

 Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes.

In [ ]:
#Creating a 2x3 matrix
a = np.array([[1, 2, 3],
              [4, 5, 6]])

#Creating a 1x3 array
b = np.array([10, 20, 30])

#Performing broadcasting addtion
result = a + b
print(a)
print()
print(b)
print()
print(result)

[[1 2 3]
 [4 5 6]]

[10 20 30]

[[11 22 33]
 [14 25 36]]


In [ ]:
#Creating a 3x3 matrix
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

#Creating a 1x3 array
b = np.array([10, 20, 30])

#Performing broadcasting subtracion
result = a-b

print(result)

[[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]


In [ ]:
#Creating a 3x3 matrix
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

#Creating a 1x3 array
b = np.array([10, 20, 30])

#Performing broadcasting subtracion
result = a*b

print(result)

[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [ ]:
#Creating a 3x3 matrix
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

#Creating a 1x3 array
b = np.array([10, 20, 30])

#Performing broadcasting subtracion
result = a**b

print(result)

[[                   1              1048576      205891132094649]
 [             1048576       95367431640625  8138741398091333632]
 [           282475249  1152921504606846976 -3535985420588157519]]


#**Concatenate**: Join a sequence of arrays along an existing axis.

# **Broadcasting:** a mechanism that allows NumPy to perform operations on arrays of different shapes


In [ ]:
a = [[5, 7, 8]]
b = [[11, 10, 21]]

c = np.concatenate((a, b), axis= 1)
c

array([[ 5,  7,  8, 11, 10, 21]])

In [ ]:
a = np.array ([5, 7, 8])
b = np.array([[11, 10, 21], [17, 21, 31]])
print(type(a))

c = a * b
c



<class 'numpy.ndarray'>


array([[ 55,  70, 168],
       [ 85, 147, 248]])